package database.mapping;
// Generated Apr 27, 2012 12:30:04 PM by Hibernate Tools 3.2.1.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.*;

/**
 * Role generated by hbm2java
 */
@Entity
@Table(name = "DEPROLE", schema = "GUEST")
public class Deprole implements java.io.Serializable {

    private long id;
    private String roleName;
    private Set<Department> department = new HashSet<Department>(0);

    public Deprole() {
    }

    public Deprole(long id) {
        this.id = id;
    }

    public Deprole(long id, String roleName, Set<Department> departments) {
        this.id = id;
        this.roleName = roleName;
        this.department = departments;
    }

    @Id
    @SequenceGenerator(name = "role_id", sequenceName = "role_id_seq")
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "role_id")
    @Column(name = "ID", unique = true, nullable = false, precision = 10, scale = 0)
    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    @Column(name = "ROLE_NAME", length = 200)
    public String getRoleName() {
        return this.roleName;
    }

    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }

    @ManyToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "role")
    public Set<Department> getDepartment() {
        return this.department;
    }

    public void setDepartment(Set<Department> department) {
        this.department = department;
    }
}
