package com.example.datamodel;
// Generated Apr 8, 2012 8:28:28 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.*;

/**
 * Department generated by hbm2java
 */
@Entity
@Table(name="DEPARTMENT"
    ,schema="GUEST"
)
public class Department  implements java.io.Serializable {


     private long id;
     private Office office;
     private Department department;
     private String depName;
     private Boolean role;
     private Set<Department> departments = new HashSet<Department>(0);
     private Set<Employee> employees = new HashSet<Employee>(0);

    public Department() {
    }

	
    public Department(long id) {
        this.id = id;
    }
    public Department(long id, Office office, Department department, String depName, Boolean role, Set<Department> departments, Set<Employee> employees) {
       this.id = id;
       this.office = office;
       this.department = department;
       this.depName = depName;
       this.role = role;
       this.departments = departments;
       this.employees = employees;
    }
   
     @Id 
     @SequenceGenerator(name="department_id",sequenceName="department_id_seq")
    @GeneratedValue(strategy=GenerationType.SEQUENCE,generator="department_id") 
    
    @Column(name="ID", unique=true, nullable=false, precision=10, scale=0)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="OFFICE_ID")
    public Office getOffice() {
        return this.office;
    }
    
    public void setOffice(Office office) {
        this.office = office;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PARENT_ID")
    public Department getDepartment() {
        return this.department;
    }
    
    public void setDepartment(Department department) {
        this.department = department;
    }
    
    @Column(name="DEP_NAME", length=40)
    public String getDepName() {
        return this.depName;
    }
    
    public void setDepName(String depName) {
        this.depName = depName;
    }
    
    @Column(name="ROLE", precision=1, scale=0)
    public Boolean getRole() {
        return this.role;
    }
    
    public void setRole(Boolean role) {
        this.role = role;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="department")
    public Set<Department> getDepartments() {
        return this.departments;
    }
    
    public void setDepartments(Set<Department> departments) {
        this.departments = departments;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="department")
    public Set<Employee> getEmployees() {
        return this.employees;
    }
    
    public void setEmployees(Set<Employee> employees) {
        this.employees = employees;
    }




}


