package com.example.datamodel;
// Generated Apr 8, 2012 8:28:28 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.*;

/**
 * Employee generated by hbm2java
 */
@Entity
@Table(name="EMPLOYEE"
    ,schema="GUEST"
)
public class Employee  implements java.io.Serializable {


     private long id;
     private Position position;
     private Department department;
     private String firstName;
     private String secondName;
     private String email;
     private String login;
     private String password;
     private Boolean isManager;
     private Set<Trf> trfs = new HashSet<Trf>(0);

    public Employee() {
    }

	
    public Employee(long id) {
        this.id = id;
    }
    public Employee(long id, Position position, Department department, String firstName, String secondName, String email, String login, String password, Boolean isManager, Set<Trf> trfs) {
       this.id = id;
       this.position = position;
       this.department = department;
       this.firstName = firstName;
       this.secondName = secondName;
       this.email = email;
       this.login = login;
       this.password = password;
       this.isManager = isManager;
       this.trfs = trfs;
    }
   
    @Id 
     @SequenceGenerator(name="destination_id",sequenceName="destination_id_seq")
    @GeneratedValue(strategy=GenerationType.SEQUENCE,generator="destination_id")
    
    @Column(name="ID", unique=true, nullable=false, precision=10, scale=0)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="POSITION_ID")
    public Position getPosition() {
        return this.position;
    }
    
    public void setPosition(Position position) {
        this.position = position;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="DEP_ID")
    public Department getDepartment() {
        return this.department;
    }
    
    public void setDepartment(Department department) {
        this.department = department;
    }
    
    @Column(name="FIRST_NAME", length=20)
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    
    @Column(name="SECOND_NAME", length=20)
    public String getSecondName() {
        return this.secondName;
    }
    
    public void setSecondName(String secondName) {
        this.secondName = secondName;
    }
    
    @Column(name="EMAIL", length=256)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    
    @Column(name="LOGIN", length=20)
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }
    
    @Column(name="PASSWORD", length=30)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    
    @Column(name="IS_MANAGER", precision=1, scale=0)
    public Boolean getIsManager() {
        return this.isManager;
    }
    
    public void setIsManager(Boolean isManager) {
        this.isManager = isManager;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="employee")
    public Set<Trf> getTrfs() {
        return this.trfs;
    }
    
    public void setTrfs(Set<Trf> trfs) {
        this.trfs = trfs;
    }




}


