package database.mapping;
// Generated Apr 25, 2012 3:55:54 PM by Hibernate Tools 3.2.1.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.*;

/**
 * City generated by hbm2java
 */
@Entity
@Table(name = "CITY", schema = "GUEST")
public class City implements java.io.Serializable {

    private long id;
    private String cityName;
    private Long countryId;
    private Set<Destination> destinations = new HashSet<Destination>(0);

    public City() {
    }

    public City(long id) {
        this.id = id;
    }

    public City(long id, String cityName, Long countryId, Set<Destination> destinations) {
        this.id = id;
        this.cityName = cityName;
        this.countryId = countryId;
        this.destinations = destinations;
    }

    @Id
    @SequenceGenerator(name = "city_id", sequenceName = "city_id_seq")
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "city_id")
    @Column(name = "ID", unique = true, nullable = false, precision = 10, scale = 0)
    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    @Column(name = "CITY_NAME", length = 20)
    public String getCityName() {
        return this.cityName;
    }

    public void setCityName(String cityName) {
        this.cityName = cityName;
    }

    @Column(name = "COUNTRY_ID", precision = 10, scale = 0)
    public Long getCountryId() {
        return this.countryId;
    }

    public void setCountryId(Long countryId) {
        this.countryId = countryId;
    }

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "city")
    public Set<Destination> getDestinations() {
        return this.destinations;
    }

    public void setDestinations(Set<Destination> destinations) {
        this.destinations = destinations;
    }
}
