package com.example.datamodel;
// Generated Apr 18, 2012 3:51:30 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.*;

/**
 * Destination generated by hbm2java
 */
@Entity
@Table(name="DESTINATION"
    ,schema="GUEST"
)
public class Destination  implements java.io.Serializable {


     private long id;
     private Long destCityId;

    public Destination() {
    }

	
    public Destination(long id) {
        this.id = id;
    }
    public Destination(long id, Long destCityId) {
       this.id = id;
       this.destCityId = destCityId;
    }
   
     @Id 
     @SequenceGenerator(name="destination_id",sequenceName="destination_id_seq")
    @GeneratedValue(strategy=GenerationType.SEQUENCE,generator="destination_id")
    
    @Column(name="ID", unique=true, nullable=false, precision=10, scale=0)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    
    @Column(name="DEST_CITY_ID", precision=10, scale=0)
    public Long getDestCityId() {
        return this.destCityId;
    }
    
    public void setDestCityId(Long destCityId) {
        this.destCityId = destCityId;
    }




}


