package com.example.datamodel;
// Generated Apr 8, 2012 8:28:28 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.*;

/**
 * Destination generated by hbm2java
 */
@Entity
@Table(name="DESTINATION"
    ,schema="GUEST"
)
public class Destination  implements java.io.Serializable {


     private long id;
     private String dname;
     private String dcountry;
     private Set<Trf> trfs = new HashSet<Trf>(0);

    public Destination() {
    }

	
    public Destination(long id) {
        this.id = id;
    }
    public Destination(long id, String dname, String dcountry, Set<Trf> trfs) {
       this.id = id;
       this.dname = dname;
       this.dcountry = dcountry;
       this.trfs = trfs;
    }
   
     @Id 
     @SequenceGenerator(name="destination_id",sequenceName="destination_id_seq")
    @GeneratedValue(strategy=GenerationType.SEQUENCE,generator="destination_id")
    
    @Column(name="ID", unique=true, nullable=false, precision=10, scale=0)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    
    @Column(name="DNAME", length=20)
    public String getDname() {
        return this.dname;
    }
    
    public void setDname(String dname) {
        this.dname = dname;
    }
    
    @Column(name="DCOUNTRY", length=15)
    public String getDcountry() {
        return this.dcountry;
    }
    
    public void setDcountry(String dcountry) {
        this.dcountry = dcountry;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="destination")
    public Set<Trf> getTrfs() {
        return this.trfs;
    }
    
    public void setTrfs(Set<Trf> trfs) {
        this.trfs = trfs;
    }




}


