package com.example.datamodel;
// Generated Apr 8, 2012 8:28:28 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.*;

/**
 * Office generated by hbm2java
 */
@Entity
@Table(name="OFFICE"
    ,schema="GUEST"
)
public class Office  implements java.io.Serializable {


     private long id;
     private String oname;
     private String ocountry;
     private Set<Department> departments = new HashSet<Department>(0);

    public Office() {
    }

	
    public Office(long id) {
        this.id = id;
    }
    public Office(long id, String oname, String ocountry, Set<Department> departments) {
       this.id = id;
       this.oname = oname;
       this.ocountry = ocountry;
       this.departments = departments;
    }
   
     @Id 
     @SequenceGenerator(name="office_id",sequenceName="office_id_seq")
    @GeneratedValue(strategy=GenerationType.SEQUENCE,generator="office_id") 
    
    @Column(name="ID", unique=true, nullable=false, precision=10, scale=0)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    
    @Column(name="ONAME", length=20)
    public String getOname() {
        return this.oname;
    }
    
    public void setOname(String oname) {
        this.oname = oname;
    }
    
    @Column(name="OCOUNTRY", length=15)
    public String getOcountry() {
        return this.ocountry;
    }
    
    public void setOcountry(String ocountry) {
        this.ocountry = ocountry;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="office")
    public Set<Department> getDepartments() {
        return this.departments;
    }
    
    public void setDepartments(Set<Department> departments) {
        this.departments = departments;
    }




}


