package com.example.datamodel;
// Generated Apr 8, 2012 8:28:28 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.*;

/**
 * Position generated by hbm2java
 */
@Entity
@Table(name="POSITION"
    ,schema="GUEST"
)
public class Position  implements java.io.Serializable {


     private long id;
     private String posName;
     private Set<Employee> employees = new HashSet<Employee>(0);

    public Position() {
    }

	
    public Position(long id) {
        this.id = id;
    }
    public Position(long id, String posName, Set<Employee> employees) {
       this.id = id;
       this.posName = posName;
       this.employees = employees;
    }
   
     @Id 
     @SequenceGenerator(name="position_id",sequenceName="position_id_seq")
    @GeneratedValue(strategy=GenerationType.SEQUENCE,generator="position_id") 
    
    @Column(name="ID", unique=true, nullable=false, precision=10, scale=0)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    
    @Column(name="POS_NAME", length=25)
    public String getPosName() {
        return this.posName;
    }
    
    public void setPosName(String posName) {
        this.posName = posName;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="position")
    public Set<Employee> getEmployees() {
        return this.employees;
    }
    
    public void setEmployees(Set<Employee> employees) {
        this.employees = employees;
    }




}


